animal = input('Please name an animal:\n')
adjective = input('Choose an adjective:\n')
exclamation = input('Write an exclamation:\n')
noun = input('Please choose a noun: \n')
verb = input('Choose a verb:\n')
second_verb = input('Choose your second verb:\n')
proper_noun = input('Please enter a proper noun:\n')
third_verb = input('Choose the third verb:\n')
fourth_verb = input('Choose the fourth verb:\n')
fifth_verb = input('Choose the fifth verb:\n')
sixth_verb = input('Choose a final verb:\n')
vowel = 'a' or 'e' or 'i' or 'o' or 'u' 
#Gathers information from the user
print('\n\n')
print('-'*20 + 'Thanksgiving Dinner MadLib' + '-'*20 +'\n\n')
print(f'The other day, I was really in trouble. It all started when I saw a very {adjective} {animal}')
print(f'{verb} down the hallway."{exclamation}!" I yelled. But all I could think to do was to {second_verb} over and over.')
print(f'Miraculously, that caused it to stop, but not before it tried to {third_verb} right in front of my family.')
print(f'{proper_noun} {fourth_verb}ed and Uncle Joe {fifth_verb}ed', end=' ') 
if noun[0] == vowel: print(f'an {noun}.', end=' ')
else: print(f'a {noun}.')
print(f'The {animal} {sixth_verb}ed out of the house, and we could finally finish our Thanksgiving dinner.\n\n')
print(f'-'*20 + 'Thank you for playing!' + '-'*20)